version: '3.8'

services:

  backend:
    container_name: backend
    image: node:16
    build:
      context: .
    command: npm start
    ports:
      - 3001:3001
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=lou_db
      - PGUSER=louai
      - PGPASSWORD=password
      - PGHOST=database
    depends_on:
      - database

  
  database:
    container_name: database
    image: "postgres:12"
    env_file:
      - ".env"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - nps_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  nps_data: {}
