version: '3.8'

services:

  backend:
    container_name: backend
    image: node:16
    env_file:
      - ".env"
    build:
      context: .
    ports:
      - "${EXTERNAL_PORT}:${EXTERNAL_PORT}"
    environment:
      - EXTERNAL_PORT=${EXTERNAL_PORT}
    depends_on:
      - database
  
  database:
    container_name: database
    image: "postgres:12"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
